name: tectonic

on:
  pull_request:
    paths:
      - '**.tex'
      - '**.yml'

env:
  TARGET_BRANCH: ${{ github.base_ref }}

jobs:
  latex-job:
    runs-on: ubuntu-latest
    name: A job to Compile Latex file
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: 'Fetch'
      run: git fetch --depth 1 origin ${TARGET_BRANCH}

    - name: 'Set up tectonic'
      uses: wtfjoke/setup-tectonic@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Compilation'
      run: |
        for file in $(git diff origin/master HEAD --diff-filter=AM --name-only -- "*.tex") ; do
          tectonic  ${file}
        done

    - name: 'Commit and push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "tectonic"
        git config --global user.email "tectonic@githubaction.diohabara.com"
        git remote set-url origin https://diohabara:${GITHUB_TOKEN}@github.com/diohabara/open_inshi.git
        git switch -c dev
        git pull origin master
        git add .
        git commit -m 'Add a new PDF'
        git push origin HEAD

